import { useEffect, useRef, useState } from 'react'
import { Icon, type IconName } from './components/Icon'
import { api, type GroundedAnswer } from './api'

type OpenAsk = (prompt?: string, submitImmediately?: boolean) => void
const quickActions: { icon: IconName; label: string; color: string }[] = [
  { icon: 'food', label: 'Restaurants', color: 'orange' }, { icon: 'train', label: 'Metro', color: 'blue' }, { icon: 'calendar', label: 'Events', color: 'pink' }, { icon: 'beach', label: 'Beaches', color: 'aqua' }, { icon: 'shop', label: 'Shopping', color: 'purple' }, { icon: 'hotel', label: 'Hotels', color: 'green' },
]
const trending = [{ name: 'Fort Kochi', kind: 'Historic area', art: 'fort' }, { name: 'Marine Drive', kind: 'Waterfront', art: 'marine' }, { name: 'Lulu Mall', kind: 'Shopping', art: 'lulu' }, { name: 'Cherai Beach', kind: 'Beach', art: 'cherai' }]
const places = [{ name: 'Fort Kochi', type: 'Historic area', rating: '4.6', distance: '1.2 km', art: 'fort' }, { name: 'Marine Drive', type: 'Waterfront', rating: '4.7', distance: '3.8 km', art: 'marine' }, { name: 'Mattancherry Palace', type: 'Museum', rating: '4.5', distance: '1.9 km', art: 'palace' }, { name: 'Cherai Beach', type: 'Beach', rating: '4.6', distance: '18 km', art: 'cherai' }]

export type SavedTrip = { id: string; title: string; summary: string; prompt: string; art: string; savedAt: string }
type ResponseCard = Omit<SavedTrip, 'savedAt'>

function responseCards(answer: string, prompt: string): ResponseCard[] {
  const lines = answer.split('\n').map((line) => line.trim().replace(/^(?:[•*-]|\d+[.)])\s*/, '')).filter(Boolean)
  const recommendations = lines.filter((line) => !/^(best fit:|please check)/i.test(line))
  const cardLines = recommendations.length > 1 ? recommendations : [answer.trim()]
  const artwork = ['fort', 'marine', 'palace', 'cherai']
  return cardLines.map((line, index) => {
    const [heading, ...detail] = line.split(/\s+[—–-]\s+|:\s+/)
    const title = heading.trim() || `Kochi idea ${index + 1}`
    const summary = (detail.join(' — ') || line).trim()
    return { id: `${prompt}-${index}-${title}`.toLocaleLowerCase().replace(/[^a-z0-9]+/g, '-'), title, summary, prompt, art: artwork[index % artwork.length] }
  })
}

function offlineTravelFallback(prompt: string): GroundedAnswer {
  const cafeRequest = /cafe|coffee|work|study/i.test(prompt)
  const answer = cafeRequest
    ? 'Fort Kochi work session — Choose a daytime café with comfortable seating and a calm pace; check its Wi-Fi and opening hours before you set out.\nMarine Drive reset — Take a short waterfront break between work blocks, then pick a nearby café for your next focused session.\nYour flexible plan — Save both ideas, then choose the one that fits your travel time and preferred atmosphere.'
    : 'Fort Kochi slow day — Build a relaxed day around heritage streets, waterfront views, and a meal break; confirm current hours before you go.\nMarine Drive pause — Add a waterfront walk when you want an easy, low-planning stop between other activities.\nYour flexible plan — Save the ideas that fit your pace, then use Ask Kochi again when the connection is available for a more tailored plan.'
  return { answer, evidence_status: 'insufficient_evidence', generation_mode: 'abstained', citations: [], suggested_followups: [], request_id: 'local-fallback' }
}

function PlaceArt({ art, large = false }: { art: string; large?: boolean }) { return <div className={`place-art ${art} ${large ? 'large' : ''}`} aria-hidden="true"><span /><i /><b /></div> }
function SectionTitle({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: React.ReactNode }) { return <div className="section-title"> <div>{eyebrow && <p>{eyebrow}</p>}<h2>{title}</h2></div>{action}</div> }

export function HomePage({ openAsk, openExplore, openPlace }: { openAsk: OpenAsk; openExplore: (filter?: string) => void; openPlace: (name: string) => void }) {
  const hour = new Date().getHours(); const greeting = hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening'
  const recommendations = ['Best breakfast nearby', 'A rainy afternoon in Kochi', 'Build my weekend itinerary', 'Hidden cafes with character']
  return <div className="page home-page"><section className="home-hero"><div><p className="eyebrow">✦ YOUR LOCAL CITY COMPANION</p><h1>{greeting}, Adi <span>👋</span></h1><p>Explore Kochi with AI — from the places you know to the ones you’ll want to remember.</p><button className="home-search" onClick={() => openAsk()}><Icon name="search" /><span>Ask anything about Kochi...</span><b><Icon name="sparkles" size={18} /></b></button></div><div className="hero-map"><p>KOCHI, KERALA</p><strong>Find a story<br />around every corner.</strong><span className="weather-pill">AI travel planning</span><span className="hero-pin one"><Icon name="pin" size={18} /></span><span className="hero-pin two"><Icon name="sparkles" size={16} /></span><div className="hero-water" /></div></section>
    <section><SectionTitle eyebrow="GET STARTED" title="What are you looking for?" /><div className="quick-grid">{quickActions.map((item) => <button key={item.label} className="quick-action" onClick={() => openAsk(`Show popular ${item.label.toLocaleLowerCase()} places in Kochi. Give each recommendation as a separate card with a practical reason to go.`, true)}><span className={item.color}><Icon name={item.icon} /></span><b>{item.label}</b></button>)}</div></section>
    <section><SectionTitle eyebrow="KOCHI HIGHLIGHTS" title="Worth exploring" action={<button className="text-button" onClick={() => openExplore()}>See all <Icon name="chevron" size={16} /></button>} /><div className="scroll-row">{trending.map((place) => <button className="trend-card" key={place.name} onClick={() => openPlace(place.name)}><PlaceArt art={place.art} /><span>{place.kind}</span><b>{place.name}</b></button>)}</div></section>
    <section className="home-split"><div><SectionTitle eyebrow="ASK KOCHI" title="A good place to start" /><div className="recommendation-list">{recommendations.map((item, index) => <button key={item} onClick={() => openAsk(item)}><span>✦</span><div><b>{item}</b><small>{['Local picks for a slow morning', 'A plan for when the weather turns', 'Food, culture, and harbour air', 'Quiet corners to settle into'][index]}</small></div><Icon name="chevron" size={17} /></button>)}</div></div><button className="nearby-card" onClick={() => openExplore()}><div><span><Icon name="location" size={19} /></span><p>EXPLORE KOCHI</p><b>Start with a<br />local highlight.</b><small>Open the guide</small></div><div className="mini-map"><i /><i /><i /></div></button></section>
  </div>
}

export function ExplorePage({ initialFilter, openPlace }: { initialFilter: string; openPlace: (name: string) => void }) {
  const [query, setQuery] = useState(initialFilter); const [sheetOpen, setSheetOpen] = useState(false); const [activeFilter, setActiveFilter] = useState('Nearby'); const [zoom, setZoom] = useState(1)
  useEffect(() => { if (initialFilter) setQuery(initialFilter) }, [initialFilter])
  const normalizedQuery = query.trim().toLocaleLowerCase()
  const filtered = places.filter((place) => !normalizedQuery || `${place.name} ${place.type}`.toLocaleLowerCase().includes(normalizedQuery))
  const chips = ['Highlights', 'Culture', 'Waterfront', 'Family', 'Shopping']
  return <div className="explore-page"><div className="explore-controls"><label className="map-search"><Icon name="search" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Browse Kochi highlights..." /><button aria-label="Filter results"><Icon name="sliders" size={18} /></button></label><div className="filter-chips">{chips.map((chip) => <button className={activeFilter === chip ? 'active' : ''} key={chip} onClick={() => setActiveFilter(chip)}>{chip}</button>)}</div></div><div className="map-surface" style={{ '--zoom': zoom } as React.CSSProperties}><div className="map-label">KOCHI<br /><span>KERALA</span></div><div className="map-river river-a" /><div className="map-river river-b" /><div className="map-road road-a" /><div className="map-road road-b" /><button className="map-user" aria-label="Current location"><span /></button>{filtered.slice(0, 4).map((place, index) => <button key={place.name} className={`map-pin pin-${index}`} aria-label={`Ask about ${place.name}`} onClick={() => openPlace(place.name)}><Icon name="pin" size={26} /><b>{place.name}</b></button>)}<div className="map-actions"><button onClick={() => setZoom(Math.min(1.18, zoom + .05))} aria-label="Zoom in"><Icon name="zoomIn" /></button><button onClick={() => setZoom(Math.max(.88, zoom - .05))} aria-label="Zoom out"><Icon name="zoomOut" /></button><button onClick={() => setActiveFilter('Nearby')} aria-label="Use current location"><Icon name="location" /></button></div></div><section className={`result-sheet ${sheetOpen ? 'open' : ''}`}><button className="sheet-handle" onClick={() => setSheetOpen(!sheetOpen)} aria-expanded={sheetOpen}><i /> <span>{sheetOpen ? 'Kochi highlights' : `${filtered.length} highlights`}</span><Icon name={sheetOpen ? 'back' : 'chevron'} size={16} /></button><div className="place-results">{query.trim().length >= 2 && !filtered.length && <p className="api-notice">No highlights match this search. Ask Kochi for a tailored suggestion.</p>}{filtered.map((place) => <article className="place-result" key={place.name}><button className="place-result-main" onClick={() => openPlace(place.name)}><PlaceArt art={place.art} /><div><b>{place.name}</b><small>{place.type} · {place.distance} away</small><span>Ask Kochi for planning ideas and confirm live details before you go.</span></div></button><div className="place-actions"><button aria-label={`Ask about ${place.name}`} onClick={() => openPlace(place.name)}><Icon name="sparkles" size={18} /></button></div></article>)}</div></section></div>
}

export function AskPage({ initialDraft, autoPrompt, focusKey, onDraftConsumed, onAutoPromptConsumed, savedTrips, saveTrip }: { initialDraft: string; autoPrompt: string; focusKey: number; onDraftConsumed: () => void; onAutoPromptConsumed: () => void; savedTrips: SavedTrip[]; saveTrip: (trip: SavedTrip) => void }) {
  type ChatMessage = { role: 'user'; text: string } | { role: 'ai'; text: string; answer?: GroundedAnswer; pending?: boolean; error?: boolean }
  const [messages, setMessages] = useState<ChatMessage[]>([]); const [draft, setDraft] = useState(''); const [scrollRequest, setScrollRequest] = useState(0); const input = useRef<HTMLInputElement>(null); const latestUserMessage = useRef<HTMLDivElement>(null)
  const send = async (prompt = draft) => { const text = prompt.trim(); if (!text) return; const pending: ChatMessage = { role: 'ai', text: 'Planning your answer…', pending: true }; setMessages((all) => [...all, { role: 'user', text }, pending]); setScrollRequest((request) => request + 1); setDraft(''); try { const answer = await api.chat(text); setMessages((all) => all.map((message) => message === pending ? { role: 'ai', text: answer.answer, answer } : message)) } catch (error) { const fallback = offlineTravelFallback(text); setMessages((all) => all.map((item) => item === pending ? { role: 'ai', text: fallback.answer, answer: fallback } : item)) } }
  useEffect(() => { if (scrollRequest) latestUserMessage.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }) }, [scrollRequest])
  useEffect(() => { if (initialDraft) { setDraft(initialDraft); onDraftConsumed() } if (autoPrompt) { void send(autoPrompt); onAutoPromptConsumed() } if (focusKey) requestAnimationFrame(() => input.current?.focus()) }, [initialDraft, autoPrompt, focusKey, onDraftConsumed, onAutoPromptConsumed])
  const prompts = ['Best cafes to work from', 'Plan my weekend', 'Things to do tonight', 'Nearest metro station', 'A family day out', 'Hidden local places']
  return <div className="ask-page"><section className={`ask-empty ${messages.length ? 'has-messages' : ''}`}>{!messages.length && <div className="ask-welcome"><span className="ask-logo"><Icon name="sparkles" size={30} /></span><p>ASK KOCHI</p><h1>How can I help today?</h1><div className="prompt-grid">{prompts.map((prompt) => <button key={prompt} onClick={() => void send(prompt)}>{prompt}<Icon name="arrow" size={16} /></button>)}</div></div>}{messages.map((message, index) => message.role === 'user' ? <div className="chat-message user" key={`${message.text}-${index}`} ref={latestUserMessage}>{message.text}</div> : <div className={`chat-message ai ${message.error ? 'error' : ''}`} key={`${message.text}-${index}`}>{!message.answer && <p>{message.text}</p>}{message.pending && <span className="chat-status">Planning your answer…</span>}{message.answer && <><p className="answer-status">{message.answer.generation_mode === 'gemini_general' ? 'AI travel guidance · confirm live details before you go' : 'Offline starter plan · check live details before you go'}</p><div className="answer-cards">{responseCards(message.answer.answer, messages[index - 1]?.role === 'user' ? messages[index - 1].text : 'Kochi plan').map((card) => { const saved = savedTrips.some((trip) => trip.id === card.id); return <article className="answer-card" key={card.id}><div><span>ASK KOCHI SUGGESTION</span><h3>{card.title}</h3><p>{card.summary}</p><button className={saved ? 'saved' : ''} onClick={() => saveTrip({ ...card, savedAt: new Date().toISOString() })} aria-pressed={saved}><Icon name="bookmark" size={16} /> {saved ? 'Saved to trips' : 'Save trip'}</button></div></article> })}</div>{message.answer.suggested_followups.length > 0 && <div className="followups">{message.answer.suggested_followups.map((followup) => <button key={followup} onClick={() => void send(followup)}>{followup}</button>)}</div>}</>}</div>)}</section><form className="chat-input" onSubmit={(event) => { event.preventDefault(); void send() }}><button type="button" aria-label="Attach an image"><Icon name="camera" /></button><button type="button" aria-label="Use current location"><Icon name="location" /></button><input ref={input} value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Ask anything about Kochi..." /><button type="button" aria-label="Use voice input"><Icon name="mic" /></button><button className="send-button" aria-label="Send message" type="submit"><Icon name="send" /></button></form></div>
}

export function TripsPage({ openPlace, savedTrips }: { openPlace: (name: string) => void; savedTrips: SavedTrip[] }) {
  const [tab, setTab] = useState('Saved')
  const sampleTrips = [{ title: 'Weekend in Kochi', summary: '2 days · 9 stops', art: 'fort' }, { title: 'Taste of Kochi', summary: '1 day · 6 stops', art: 'food' }, { title: 'Family day out', summary: '1 day · 5 stops', art: 'cherai' }]
  const trips = tab === 'Saved' ? savedTrips : sampleTrips
  return <div className="page trips-page"><div className="page-intro"><p className="eyebrow">YOUR PLANS</p><h1>Trips, saved.</h1><p>Keep the days you want to return to — and make room for the next one.</p></div><div className="trip-summary"><div><span>2</span><small>Upcoming trips</small></div><div><span>{savedTrips.length}</span><small>Saved trips</small></div><div><span>7</span><small>Completed days</small></div></div><div className="tab-row">{['Upcoming', 'Saved', 'Recent'].map((item) => <button className={tab === item ? 'active' : ''} key={item} onClick={() => setTab(item)}>{item}</button>)}</div><section><SectionTitle title={tab === 'Upcoming' ? 'Coming up' : tab === 'Saved' ? 'Saved trips' : 'Recent trips'} action={<button className="text-button"><Icon name="plus" size={16} /> New trip</button>} />{!trips.length ? <div className="empty-trips"><Icon name="bookmark" size={22} /><b>No saved trips yet</b><span>Save a card from an Ask Kochi response and it will appear here.</span></div> : <div className="trip-list">{trips.map((trip) => <button key={trip.title + trip.summary} className="trip-list-card" onClick={() => openPlace(trip.title)}><PlaceArt art={trip.art} /><div><b>{trip.title}</b><span>{trip.summary}</span><small><Icon name="clock" size={13} /> {tab === 'Saved' ? 'Saved from Ask Kochi' : 'Last updated 2 days ago'}</small></div><Icon name="chevron" size={18} /></button>)}</div>}</section><section className="saved-places"><SectionTitle eyebrow="YOUR COLLECTION" title="Saved places" action={<button className="text-button">View all <Icon name="chevron" size={16} /></button>} /><div>{places.slice(0, 3).map((place) => <button onClick={() => openPlace(place.name)} key={place.name}><PlaceArt art={place.art} /><span>{place.name}</span></button>)}</div></section></div>
}

export function ProfilePage({ darkMode, setDarkMode }: { darkMode: boolean; setDarkMode: (value: boolean) => void }) { const [notifications, setNotifications] = useState(true); return <div className="page profile-page"><div className="profile-heading"><div className="avatar-large">A</div><div><p className="eyebrow">ASK KOCHI</p><h1>Your travel companion</h1><span>A lightweight AI planning MVP.</span></div></div><div className="profile-stats"><div><b>Kochi</b><span>City-specific guidance</span></div><div><b>Plan</b><span>Ideas for your day</span></div><div><b>Private</b><span>No sign-up required</span></div></div><section className="profile-section"><SectionTitle title="Preferences" /><ToggleRow label="Dark mode" icon="sparkles" on={darkMode} setOn={setDarkMode} /><ToggleRow label="Notifications" icon="calendar" on={notifications} setOn={setNotifications} /><button className="settings-row"><Icon name="location" /><span>Location permissions</span><small>Optional</small><Icon name="chevron" /></button><button className="settings-row"><Icon name="user" /><span>Language</span><small>English</small><Icon name="chevron" /></button></section><section className="profile-section"><SectionTitle title="About" /><button className="settings-row"><Icon name="share" /><span>Privacy & terms</span><Icon name="chevron" /></button><button className="settings-row"><Icon name="more" /><span>Help & feedback</span><Icon name="chevron" /></button></section></div> }
function ToggleRow({ label, icon, on, setOn }: { label: string; icon: IconName; on: boolean; setOn: (value: boolean) => void }) { return <button className="settings-row" onClick={() => setOn(!on)}><Icon name={icon} /><span>{label}</span><i className={`toggle ${on ? 'on' : ''}`}><b /></i></button> }

export function PlacePage({ name, goBack, openAsk }: { name: string; goBack: () => void; openAsk: OpenAsk }) { const place = places.find((item) => item.name === name) ?? { name, type: 'Kochi highlight', rating: 'Local guide', distance: 'Kochi', art: 'fort' }; return <div className="place-page"><div className="place-hero"><PlaceArt art={place.art} large /><div className="place-nav"><button onClick={goBack} aria-label="Go back"><Icon name="back" /></button><div><button aria-label="Save place"><Icon name="bookmark" /></button><button aria-label="Share place"><Icon name="share" /></button></div></div></div><div className="place-content"><p className="eyebrow">{place.type.toUpperCase()}</p><div className="place-heading"><h1>{place.name}</h1><span><Icon name="star" size={15} /> {place.rating} <small>(local guide)</small></span></div><p className="place-description">Ask Kochi can help you shape a visit around this area. Confirm opening hours, directions, and travel details before you go.</p><div className="place-buttons"><button className="primary" onClick={() => openAsk(`Tell me more about ${place.name}`)}><Icon name="sparkles" size={17} /> Ask AI about this place</button><button><Icon name="directions" size={17} /> Navigate</button></div><section className="detail-grid"><article><Icon name="clock" /><div><b>Opening hours</b><span>Check the venue directly for current hours</span></div></article><article><Icon name="pin" /><div><b>Area</b><span>{place.distance}, Kochi, Kerala</span></div></article><article><Icon name="train" /><div><b>Nearest metro</b><span>Check a live map before setting off</span></div></article><article><Icon name="phone" /><div><b>Contact</b><span>Check the official venue listing</span></div></article></section><section className="ai-summary"><span><Icon name="sparkles" /></span><div><p>ASK KOCHI</p><b>Need more detail?</b><small>Use the chat for a practical plan, then confirm live details with the venue or map provider.</small></div></section><section><SectionTitle title="Nearby places" /><div className="nearby-place-grid">{places.filter((item) => item.name !== name).slice(0, 3).map((item) => <article key={item.name}><PlaceArt art={item.art} /><b>{item.name}</b><span>{item.distance} away</span></article>)}</div></section></div></div> }
